// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp6cOhbeIoHJYnb0D9p_Mq-UDXrQgmGOA',
    appId: '1:401365494048:android:bbc5cd12fc16da86674f45',
    messagingSenderId: '401365494048',
    projectId: 'taxi-passau-c2741',
    databaseURL: 'https://taxi-passau-c2741-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-passau-c2741.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvNkZ4o5SK0f6v5IIFPSf3IoPkoRlNG4Y',
    appId: '1:401365494048:ios:3207fd666ad66c2f674f45',
    messagingSenderId: '401365494048',
    projectId: 'taxi-passau-c2741',
    databaseURL: 'https://taxi-passau-c2741-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-passau-c2741.firebasestorage.app',
    androidClientId: '401365494048-5q3k5get0kkm4i1ob356904o5lb4b6vs.apps.googleusercontent.com',
    iosClientId: '401365494048-e0de0bbabfolhaq0ucf3747cnslk8qol.apps.googleusercontent.com',
    iosBundleId: 'com.taxipassau.ios',
  );

}